//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookSupply.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public decimal UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public decimal EmployeeId { get; set; }
        public decimal JobId { get; set; }
        public decimal StatusId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Job Job { get; set; }
    }
}
