//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookSupply.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public decimal OrderId { get; set; }
        public decimal ISBN { get; set; }
        public decimal QuantityOrdered { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Order Order { get; set; }
    }
}
